using System;

namespace SkyTrakWrapper
{
	public enum RIPEErrType
	{
		RIPE_ERR_SUCCESS,
		RIPE_ERR_RESOURCE_ERROR,
		RIPE_ERR_BUSY,
		RIPE_ERR_PARAMETER_INVALID,
		RIPE_ERR_UNAVAILABLE,
		RIPE_ERR_BOX_NOT_CONNECTED,
		RIPE_ERR_FAIL_UNKNOWN,
		RIPE_ERR_LAST
	}
}